# Generated by Django 2.2 on 2021-06-12 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favBooks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='favorites',
            new_name='favorited_by',
        ),
    ]
